version: '3'
services:
  app:
    image: mustafaneto/ecommerce-mvc
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm start
